apiVersion: v1
kind: Pod
metadata:
  name: share-pod
  labels:
    app: share-pod
spec:
  volumes:
    - name: host-volume
      hostPath:
        path: /home/docker/pod-volume
  containers:
    - image: nginx:alpine
      name: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: host-volume
      command: ["/bin/sh"]
      args: ["-c","echo Introduction to Kubernetes > /host-vol/index.html; slepp 3600;done"]
